# Generated by Django 3.2.15 on 2022-10-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travalapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='price',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
    ]
